language: node_js
node_js:
- 6
- 8
- stable
deploy:
  provider: npm
  email: nathan@nfriedly.com
  api_key:
    secure: KYoYXfYT3h4qZznrxV2DRmbmkBImdhe5Vz9uExSb6O6enKVWwO/3FVI+NUkAyMRyENgXAieix0ybPrbkHfbmPRpY3OBL/LBIQtK2uWHGwi0JxW7fwOP+Z2mGSwEMK3EAOfQuYx9OhOmT4F+Nvsjf3a6Bt0223Ua1LoHhZicd56M=
  on:
    tags: true
    repo: nfriedly/express-rate-limit
