# /.github/workflows/test.yaml
# Test everything with the library

name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_library:
    name: Build the library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Build the library
        run: |
          npm ci
          npm pack
      - name: Use the built library to run extra tests
        run: |
          mv ./express-rate-limit*.tgz ../express-rate-limit.tgz
          git fetch --no-tags --depth=1 origin tests
          git checkout tests
          cp ../express-rate-limit.tgz ./assets/

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/
          git commit --allow-empty --message "chore: update library tarball"
          git push
  test_library:
    name: Test the library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Test the library
        run: |
          npm ci
          npm test
  test_imports:
    name: Import Variations
    runs-on: ubuntu-latest
    needs: build_library
    steps:
      - name: Checkout the `tests` branch
        uses: actions/checkout@v2
        with:
          ref: tests
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Test various imports with the library
        run: |
          cd test/import-tests
          bash run-all-tests
  test_stores:
    name: External Stores
    runs-on: ubuntu-latest
    needs: build_library
    services:
      rate-limit-redis:
        image: redis
        ports:
          - 6379:6379
      rate-limit-mongo:
        image: mongo
        ports:
          - 27017:27017
      rate-limit-memcached:
        image: memcached
        ports:
          - 11211:11211
    steps:
      - name: Checkout the `tests` branch
        uses: actions/checkout@v2
        with:
          ref: tests
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Test various external stores with the library
        run: |
          cd test/store-tests
          bash run-all-tests
